# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Install pytest'
  inputs:
    targetType: 'inline'
    script: |
      pip install pytest allure-pytest
- task: Bash@3
  displayName: 'Install allurectl'
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O ./allurectl
      chmod +x ./allurectl

- script: |

  displayName: 'Run a one-line script'
  env:
    ALLURE_RESULTS: "./allure-results"
    ALLURE_LAUNCH_NAME: "${CI_PROJECT_NAME} - ${CI_COMMIT_SHORT_SHA}"
    TEST_BRANCH: $(Build.SourceBranchName)
    ALLURE_LAUNCH_TAGS: "$(Build.SourceBranchName), azure"

- script: |
    echo '$(Build.SourceBranchName)'
  displayName: 'Run a multi-line script'
